//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/dependent/dependencies.txt`
//

actual fun ac_platformDependentAc(): String = "apJvm"
fun apJvm_platformOnly() = "apJvm"

fun apJvmTest() {
  ac_platformIndependentAc()
  ac_platformDependentAc()
  apJvm_platformOnly()
}
