//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/dependent/dependencies.txt`
//

actual fun bc_platformDependentBc(): String = "bpJs"
fun bpJs_platformOnly() = "bpJs"

fun bpJsTest() {
  bc_platformIndependentBc()
  bc_platformDependentBc()
  bpJs_platformOnly()
}
