//
// DON'T EDIT! This file is GENERATED by `MppJpsIncTestsGenerator` (runs by generateTests)
// from `incremental/multiplatform/multiModule/dependent/dependencies.txt`
//

actual fun bc_platformDependentBc(): String = "bpJvm"
fun bpJvm_platformOnly() = "bpJvm"

fun bpJvmTest() {
  bc_platformIndependentBc()
  bc_platformDependentBc()
  bpJvm_platformOnly()
  JavaClass().doStuff()
}
